### ISSUE TITLE
express 无法获取请求的body参数 

### ISSUE THREAD

**Issue by HeRedBo** [star7th/htq#1]
express4.x 版本后无法使用 获取post 的请求的参数 
克隆代码下执行后发现无法获取到post 请求的参数 
网上找一些资料后 发现如下解决方案：
https://www.npmjs.com/package/connect-multiparty
需要使用 connect-multiparty 替换以前的 body-parser

**Comment by star7th** [comment]
我在想要不要直接改package.json 里的版本，要求express只能用4.14.0会不会更便捷些

**Comment by star7th** [comment]
毕竟它每次升级若不向后兼容，我这里的代码都得改。你觉得呢

**Comment by HeRedBo** [comment]
我觉得还是改一下也没啥事的啊 毕竟 express 现在都没啥改动了 现在 express 团队都去搞 KOA2 框架了

**Comment by HeRedBo** [comment]
不过 最好还是迎合最新的比较好点吧

**Comment by star7th** [comment]
现在才想起要关闭这个问题。其实问题早解决了。更新即可。
